[build]
  publish = "public"              # tells Netlify where the site lives
  functions = "netlify/functions" # tells Netlify where serverless functions are

[[redirects]]
  from = "/api/webhooks/:id/:token"
  to = "/.netlify/functions/webhook?token=:token"
  status = 200
  
