[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/webhooks/:id/:token"
  to = "/.netlify/functions/webhook?token=:token"
  status = 200

[[redirects]]
  from = "/api/logs"
  to = "/.netlify/functions/get-logs"
  status = 200
  
